services:
  database:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: bingus1234
      POSTGRES_DB: prj-entrades
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - prj-entrades

  main-back:
    build:
      context: ./backend/main-back
      dockerfile: Dockerfile
    volumes:
      - ./backend/main-back:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - database
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: database
      DB_PORT: 5432
      DB_DATABASE: prj-entrades
      DB_USERNAME: user
      DB_PASSWORD: bingus1234
      SOCKETS_BASE_URL: http://sockets:4000
    networks:
      - prj-entrades

  sockets:
    build:
      context: ./backend/sockets-server
      dockerfile: Dockerfile
    environment:
      - PORT=4000
      - CORS_ORIGIN=*
    ports:
      - "4000:4000"
    networks:
      - prj-entrades

  frontend:
    build:
      context: ./frontend
      target: dev # Points to the 'dev' stage in Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=3000
      - CHOKIDAR_USEPOLLING=true
      - NUXT_DEVTOOLS=true
    networks:
      - prj-entrades

volumes:
  db_data:

networks:
  prj-entrades:
    driver: bridge
    name: prj-entrades
